"""Single Co-DINO Swin-L transfer; preserves official RGB normalization/aspect ratio."""
from pathlib import Path
ROOT=Path('/home/fbohan/AIC')
_base_=str(ROOT/'checkpoints/gpu6_storage/codino/vendor/Co-DETR/projects/configs/co_dino/co_dino_5scale_swin_large_16e_o365tococo.py')
classes=('person','boat','animal','seat','sign','bicycle','car','ball','light','garbage can','uav','tricycle')
model=dict(
    query_head=dict(num_classes=12,dn_cfg=dict(group_cfg=dict(num_dn_queries=100))),
    roi_head=[dict(type='CoStandardRoIHead',bbox_roi_extractor=dict(type='SingleRoIExtractor',roi_layer=dict(type='RoIAlign',output_size=7,sampling_ratio=0),out_channels=256,featmap_strides=[4,8,16,32,64],finest_scale=56),bbox_head=dict(type='Shared2FCBBoxHead',in_channels=256,fc_out_channels=1024,roi_feat_size=7,num_classes=12,bbox_coder=dict(type='DeltaXYWHBBoxCoder',target_means=[0.,0.,0.,0.],target_stds=[.1,.1,.2,.2]),reg_class_agnostic=False,reg_decoded_bbox=True,loss_cls=dict(type='CrossEntropyLoss',use_sigmoid=False,loss_weight=12.),loss_bbox=dict(type='GIoULoss',loss_weight=120.)))],
    bbox_head=[dict(type='CoATSSHead',num_classes=12,in_channels=256,stacked_convs=1,feat_channels=256,anchor_generator=dict(type='AnchorGenerator',ratios=[1.],octave_base_scale=8,scales_per_octave=1,strides=[4,8,16,32,64,128]),bbox_coder=dict(type='DeltaXYWHBBoxCoder',target_means=[0.,0.,0.,0.],target_stds=[.1,.1,.2,.2]),loss_cls=dict(type='FocalLoss',use_sigmoid=True,gamma=2.,alpha=.25,loss_weight=12.),loss_bbox=dict(type='GIoULoss',loss_weight=24.),loss_centerness=dict(type='CrossEntropyLoss',use_sigmoid=True,loss_weight=12.))],
    test_cfg=[dict(max_per_img=100,nms=None),dict(rpn=dict(nms_pre=1000,max_per_img=1000,nms=dict(type='nms',iou_threshold=.7),min_bbox_size=0),rcnn=dict(score_thr=0.,nms=dict(type='nms',iou_threshold=.5),max_per_img=100)),dict(nms_pre=1000,min_bbox_size=0,score_thr=0.,nms=dict(type='nms',iou_threshold=.6),max_per_img=100)])
img_norm_cfg=dict(mean=[123.675,116.28,103.53],std=[58.395,57.12,57.375],to_rgb=True)
train_pipeline=[dict(type='LoadImageFromFile'),dict(type='LoadAnnotations',with_bbox=True),dict(type='RandomFlip',flip_ratio=.5),dict(type='Resize',img_scale=[(1024,576),(1138,640),(1310,736)],multiscale_mode='value',keep_ratio=True),dict(type='Normalize',**img_norm_cfg),dict(type='Pad',size_divisor=32),dict(type='DefaultFormatBundle'),dict(type='Collect',keys=['img','gt_bboxes','gt_labels'])]
test_pipeline=[dict(type='LoadImageFromFile'),dict(type='MultiScaleFlipAug',img_scale=(1422,800),flip=False,transforms=[dict(type='Resize',keep_ratio=True),dict(type='RandomFlip'),dict(type='Normalize',**img_norm_cfg),dict(type='Pad',size_divisor=32),dict(type='ImageToTensor',keys=['img']),dict(type='Collect',keys=['img'])])]
data=dict(samples_per_gpu=1,workers_per_gpu=2,train=dict(type='CocoDataset',ann_file=str(ROOT/'data/annotations/train1600.json'),img_prefix=str(ROOT/'data/train')+'/',classes=classes,filter_empty_gt=False,pipeline=train_pipeline),val=dict(type='CocoDataset',ann_file=str(ROOT/'data/annotations/val400.json'),img_prefix=str(ROOT/'data/train')+'/',classes=classes,pipeline=test_pipeline,test_mode=True),test=dict(type='CocoDataset',ann_file=str(ROOT/'data/annotations/val400.json'),img_prefix=str(ROOT/'data/train')+'/',classes=classes,pipeline=test_pipeline,test_mode=True))
load_from=None
