__include__:
- /home/fbohan/AIC/configs/rgb1600.yml
ema:
  decay: 0.999
  warmups: 1000
epochs: 12
eval_spatial_size:
- 800
- 800
gpu_memory_limit_gib: 8.5
gradient_accumulation_steps: 1
min_lr_factor: 0.1
optimizer:
  lr: 1.0e-05
  params:
  - lr: 1.0e-07
    params: ^(?=.*backbone)(?!.*norm|bn).*$
  - params: ^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$
    weight_decay: 0.0
output_dir: /home/fbohan/AIC/runs/contextfull800
train_dataloader:
  collate_fn:
    base_size: 800
    base_size_repeat: 3
    stop_epoch: 999
  dataset:
    transforms:
      ops:
      - type: RandomPhotometricDistort
        p: 0.5
      - type: ContextTargetViews
        p: 0
        min_fraction: 0.55
        max_fraction: 0.8
        max_target_area_fraction: 0.0025
        density_radius: 0.12
      - type: SanitizeBoundingBoxes
        min_size: 1
      - type: RandomHorizontalFlip
      - type: Resize
        size:
        - 800
        - 800
      - type: SanitizeBoundingBoxes
        min_size: 1
      - type: ConvertPILImage
        dtype: float32
        scale: true
      - type: ConvertBoxes
        fmt: cxcywh
        normalize: true
      policy:
        epoch: 999
  total_batch_size: 9
val_dataloader:
  dataset:
    transforms:
      ops:
      - size:
        - 800
        - 800
        type: Resize
      - dtype: float32
        scale: true
        type: ConvertPILImage
  total_batch_size: 6
warmup_epochs: 1
find_unused_parameters: true
smoke_steps: 6
smoke_empty_rank: 2
sync_bn: false
