__include__: ['./scene_obj365_pool800.yml']
output_dir: /home/fbohan/AIC/runs/full2000_obj365_pool800
validate: false
train_dataloader:
  dataset:
    ann_file: /home/fbohan/AIC/data/annotations/train2000.json
