__include__: ['./scene_whole_head_real.yml']
output_dir: /home/fbohan/AIC/runs/scene_whole_head_sham
summary_dir: /home/fbohan/AIC/experiments/whole_frame_head/scene_whole_head_sham/summary
WholeFrameHeadDFINE:
  mode: sham
